name: Cargo Doc

on:
  push:
    branches: [ "*" ]

jobs:
  build_docs:
    name: Generate and push docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: actions-rs/cargo@v1
        with:
          command: doc
          args: --target-dir docs 
      - uses: stefanzweifel/git-auto-commit-action@v4
        with: 
          commit_message: Automated Doc Update